apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retained-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # volumeMode: Filesystem
  resources:
    requests:
      storage: 150Mi
  storageClassName: fast-storage
  volumeName: persistent-volume
