name: Deploy AWS Ansible based runners

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/github-runners

permissions:
  id-token: write
  contents: read

jobs:
  build :
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PACKER_IAM_ROLE }}
          aws-region: us-east-1

      - name: Setup ansible
        run: |
          sudo apt-get update 
          sudo apt-get install -y ansible

      - name: Setup packer
        uses: hashicorp/setup-packer@v3.2.0

      - name: Get GitHub Actions IP ranges
        run: |
          curl -s https://api.github.com/meta \
            | jq -r '.actions | map("\"" + . + "\"") | join(",")' \
            > github_actions_cidrs.txt

          echo "github_actions_cidrs = [$(cat github_actions_cidrs.txt)]" > cidrs.pkrvars.hcl

      - name: Build AMI with packer
        run: |
          cd github-runners-aws/github-runners-ansible-aws/packer
          packer init .
          packer validate -var-file=../../../cidrs.pkrvars.hcl github-runner.pkr.hcl
          packer build -var-file=../../../cidrs.pkrvars.hcl github-runner.pkr.hcl

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_IAM_ROLE }}
          aws-region: ${{ secrets.ECR_REGION }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform deploy infra
        run: |
          cd github-runners-aws/github-runners-ansible-aws/terraform
          terraform init 
          terraform plan
          terraform apply \
          -var="runner_count=5" \
          -var="ami=ami-0abc123456789" \
          -var="instance_type=t3.medium"

      - name: Deploy to EKS
        run: |
          echo "Deploying to EKS cluster..."