name: Deploy simulation

on:
  workflow_dispatch:
  push:
    branches:
      - feature/github-runners

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: feature/github-runners

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_IAM_ROLE }}
          aws-region: ${{ secrets.ECR_REGION }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.ECR_REPO_URI}}:${{ github.sha }} \
            -t ${{ secrets.ECR_REPO_URI}}:latest \
            -f emr-simulation/back-end/Dockerfile \
            emr-simulation/back-end

      - name: Push image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URI }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPO_URI }}:latest

  test:
    runs-on: standard
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: feature/github-runners
          path: emr-simulation

      - name: Activate virtual environment 
        run: |
          cd emr-simulation/back-end
          python -m venv .venv
          source .venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd emr-simulation/back-end
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run simulation
        run: |
          cd emr-simulation/back-end
          source .venv/bin/activate
          python manage.py runserver

