name: Deploy simulation

on:
  workflow_dispatch:
  push:
    branches:
      - feature/github-runners

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: feature/github-runners

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_IAM_ROLE }}
          aws-region: ${{ secrets.ECR_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.ECR_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URI }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.ECR_REPO_URI}}:api-${{ github.sha }} \
            -t ${{ secrets.ECR_REPO_URI}}:api-latest \
            -f emr-simulation/back-end/Dockerfile \
            emr-simulation/back-end

      - name: Push image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URI }}:api-${{ github.sha }}
          docker push ${{ secrets.ECR_REPO_URI }}:api-latest

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: feature/github-runners

      - name: Activate virtual environment & install dependencies
        run: |
          cd emr-simulation/back-end
          python -m pip install -r requirements.txt
          
      - name: Run simulation
        run: |
          cd emr-simulation/back-end/
          python -m simulation.run_simulation

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: feature/github-runners

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_IAM_ROLE }}
          aws-region: ${{ secrets.ECR_REGION }}

      - name: Deploy to AWS (ECS, EKS, etc.)
        run: |
          # Add your deployment commands here, e.g., using AWS CLI or SDK to deploy the Docker image
          echo "Deploying to AWS..."