name: Deploy simulation

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: standard

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          path: emr-simulation