name: Test GKE ARC Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/github-runners

jobs:
  test:
    runs-on: standard
    steps:
      - name: Check runner
        run: |
          echo "Running inside GKE ARC runner"
          uname -a
          docker version