apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 676005808259.dkr.ecr.us-east-1.amazonaws.com/devops-training:api-latest
        imagePullPolicy: Always
        command: ["python"]
        args: ["manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
