apiVersion: v1
kind: Service
metadata:
  name: api-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
# This annotation ensures that the load balancer created by 
# AWS is internet-facing, allowing external access to the service.
# if recreated, you would need to tag a subnet with the next annotation to ensure 
# the load balancer is created in a subnet that has a route to the internet gateway.
# kubernetes.io/role/internal-elb = 1
# kubernetes.io/role/elb = 1
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000